vim.keymap.set("n", "<leader>ox", function() require("trouble").toggle() end)
vim.keymap.set("n", "<leader>ow", function() require("trouble").toggle("workspace_diagnostics") end)
vim.keymap.set("n", "<leader>od", function() require("trouble").toggle("document_diagnostics") end)
vim.keymap.set("n", "<leader>oq", function() require("trouble").toggle("quickfix") end)
vim.keymap.set("n", "<leader>ol", function() require("trouble").toggle("loclist") end)
vim.keymap.set("n", "gR", function() require("trouble").toggle("lsp_references") end)
